dist: xenial
language: java
jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk10
  - openjdk11
script:
  - mvn clean install
after_success:
  - mvn clean test jacoco:report coveralls:report -DrepoToken=$REPO_TOKEN