version: 2
orbs:
  maven: circleci/maven@1.0.3
  codecov: codecov/codecov@1.1.1
  coveralls: coveralls/coveralls@1.0.6
  sonarcloud: sonarsource/sonarcloud@1.0.2
jobs:
  maven/test:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - run:
          name: Generate Cache Checksum
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
      - restore_cache:
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - run:
          name: Install Dependencies
          command: mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline
      - run:
          name: Run Tests
          command: mvn verify
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - store_test_results:
          path: target/surefire-reports
workflows:
  maven_test:
    jobs:
      - maven/test
  version: 2
