version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  steps:
    - checkout
    - run:
        name: Generate Cache Checksum
        command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
    - restore_cache:
        key: maven-{{ checksum "/tmp/maven_cache_seed" }}
    - run:
        name: Install Dependencies
        command: mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline
    - run:
        name: Run Tests
        command: mvn verify
    - save_cache:
        paths:
          - ~/.m2
        key: maven-{{ checksum "/tmp/maven_cache_seed" }}
    - store_test_results:
        path: target/surefire-reports

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
